name: BungeeSigns
version: ${project.version}
main: de.lunoro.bungeesigns.BungeeSigns
api-version: 1.17
authors: [ Lunoro ]
description: a plugin to switch servers in a bungee network via signs
commands:
  editSign:
